# coding: utf-8

module ComingElections
  ELECTION_TYPES = %w(general by-election municipal)

  SCOPES = [
    'cities and (southern) towns and villages',
    'cities, towns and villages',
    'even-numbered rural municipalities',
    'odd-numbered rural municipalities',
    'hamlets',
    'municipalities',
    'resort villages',
    'rural municipalities',
    'taxed communities',
    'tlicho community governments',
    'urban municipalities',
  ]

  PROVINCES = [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
  ]

  TERRITORIES = [
    'Northwest Territories',
    'Nunavut',
    'Yukon',
    # Municipalities
    'Bedford',
    'Bromont',
    'Cowansville',
    'Magog',
    'Vancouver',
    'Winnipeg',
    'Montreal',
    'Iqaluit'
  ]

  MUNICIPALITIES = [
    # Alberta
    'Hinton',
    'Lacombe County',
    'Lethbridge',
    'Rocky View County',
    'Stony Plain',
    'Yellowhead County',
    # Manitoba
    'Winnipeg', # River Heights-Fort Garry
    # Ontario
    'Ottawa', # Orléans
    # Quebec
    'Gatineau', # Orée-du-Parc
    'Montreal', # Marie-Victorin, Outremont, Rivière-des-Prairies
    'Quebec City',
  ]

  JURISDICTIONS = [
    'Canada',
  ] + PROVINCES + TERRITORIES

  # @see https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-ca/
  DIVISIONS = {
    "Canada" => [
      "Avalon",
      "Bonavista–Gander–Grand Falls–Windsor",
      "Humber–St. Barbe–Baie Verte",
      "Labrador",
      "Random–Burin–St. George's",
      "St. John's East",
      "St. John's South–Mount Pearl",
      "Cardigan",
      "Charlottetown",
      "Egmont",
      "Malpeque",
      "Cape Breton–Canso",
      "Central Nova",
      "Dartmouth–Cole Harbour",
      "Halifax",
      "Halifax West",
      "Kings–Hants",
      "Cumberland–Colchester–Musquodoboit Valley",
      "Sackville–Eastern Shore",
      "South Shore–St. Margaret's",
      "Sydney–Victoria",
      "West Nova",
      "Acadie–Bathurst",
      "Beauséjour",
      "Fredericton",
      "Fundy Royal",
      "Madawaska–Restigouche",
      "Miramichi",
      "Moncton–Riverview–Dieppe",
      "New Brunswick Southwest",
      "Saint John",
      "Tobique–Mactaquac",
      "Abitibi–Témiscamingue",
      "Ahuntsic",
      "Alfred-Pellan",
      "Argenteuil–Papineau–Mirabel",
      "Beauce",
      "Beauharnois–Salaberry",
      "Beauport–Limoilou",
      "Berthier–Maskinongé",
      "Bourassa",
      "Brome–Missisquoi",
      "Brossard–La Prairie",
      "Chambly–Borduas",
      "Charlesbourg–Haute-Saint-Charles",
      "Montmorency–Charlevoix–Haute-Côte-Nord",
      "Châteauguay–Saint-Constant",
      "Chicoutimi–Le Fjord",
      "Compton–Stanstead",
      "Drummond",
      "Gaspésie–Îles-de-la-Madeleine",
      "Gatineau",
      "Hochelaga",
      "Honoré-Mercier",
      "Hull–Aylmer",
      "Jeanne-Le Ber",
      "Joliette",
      "Jonquière–Alma",
      "Lac-Saint-Louis",
      "La Pointe-de-l'Île",
      "LaSalle–Émard",
      "Laurentides–Labelle",
      "Laurier–Sainte-Marie",
      "Laval",
      "Laval–Les Îles",
      "Lévis–Bellechasse",
      "Longueuil–Pierre-Boucher",
      "Lotbinière–Chutes-de-la-Chaudière",
      "Louis-Hébert",
      "Louis-Saint-Laurent",
      "Manicouagan",
      "Marc-Aurèle-Fortin",
      "Haute-Gaspésie–La Mitis–Matane–Matapédia",
      "Mégantic–L'Érable",
      "Montcalm",
      "Mount Royal",
      "Notre-Dame-de-Grâce–Lachine",
      "Abitibi–Baie-James–Nunavik–Eeyou",
      "Outremont",
      "Papineau",
      "Pierrefonds–Dollard",
      "Pontiac",
      "Portneuf–Jacques-Cartier",
      "Québec",
      "Repentigny",
      "Bas-Richelieu–Nicolet–Bécancour",
      "Richmond–Arthabaska",
      "Rimouski-Neigette–Témiscouata–Les Basques",
      "Rivière-des-Mille-Îles",
      "Montmagny–L'Islet–Kamouraska–Rivière-du-Loup",
      "Rivière-du-Nord",
      "Roberval–Lac-Saint-Jean",
      "Rosemont–La Petite-Patrie",
      "Saint-Bruno–Saint-Hubert",
      "Saint-Hyacinthe–Bagot",
      "Saint-Jean",
      "Saint-Lambert",
      "Saint-Laurent–Cartierville",
      "Saint-Léonard–Saint-Michel",
      "Saint-Maurice–Champlain",
      "Shefford",
      "Sherbrooke",
      "Terrebonne–Blainville",
      "Trois-Rivières",
      "Vaudreuil-Soulanges",
      "Verchères–Les Patriotes",
      "Westmount–Ville-Marie",
      "Ajax–Pickering",
      "Algoma–Manitoulin–Kapuskasing",
      "Ancaster–Dundas–Flamborough–Westdale",
      "Barrie",
      "Beaches–East York",
      "Bramalea–Gore–Malton",
      "Brampton–Springdale",
      "Brampton West",
      "Brant",
      "Burlington",
      "Cambridge",
      "Carleton–Mississippi Mills",
      "Chatham-Kent–Essex",
      "Durham",
      "Davenport",
      "Don Valley East",
      "Don Valley West",
      "Dufferin–Caledon",
      "Eglinton–Lawrence",
      "Elgin–Middlesex–London",
      "Essex",
      "Etobicoke Centre",
      "Etobicoke–Lakeshore",
      "Etobicoke North",
      "Glengarry–Prescott–Russell",
      "Bruce–Grey–Owen Sound",
      "Guelph",
      "Haldimand–Norfolk",
      "Haliburton–Kawartha Lakes–Brock",
      "Halton",
      "Hamilton Centre",
      "Hamilton East–Stoney Creek",
      "Hamilton Mountain",
      "Huron–Bruce",
      "Kenora",
      "Kingston and the Islands",
      "Kitchener Centre",
      "Kitchener–Conestoga",
      "Kitchener–Waterloo",
      "Lanark–Frontenac–Lennox and Addington",
      "Leeds–Grenville",
      "London–Fanshawe",
      "London North Centre",
      "London West",
      "Markham–Unionville",
      "Lambton–Kent–Middlesex",
      "Mississauga–Brampton South",
      "Mississauga East–Cooksville",
      "Mississauga–Erindale",
      "Mississauga South",
      "Mississauga–Streetsville",
      "Nepean–Carleton",
      "Newmarket–Aurora",
      "Niagara Falls",
      "Niagara West–Glanbrook",
      "Nickel Belt",
      "Nipissing–Timiskaming",
      "Northumberland–Quinte West",
      "Oak Ridges–Markham",
      "Oakville",
      "Oshawa",
      "Ottawa Centre",
      "Ottawa–Orléans",
      "Ottawa South",
      "Ottawa–Vanier",
      "Ottawa West–Nepean",
      "Oxford",
      "Parkdale–High Park",
      "Parry Sound–Muskoka",
      "Perth–Wellington",
      "Peterborough",
      "Pickering–Scarborough East",
      "Prince Edward–Hastings",
      "Renfrew–Nipissing–Pembroke",
      "Richmond Hill",
      "St. Catharines",
      "St. Paul's",
      "Sarnia–Lambton",
      "Sault Ste. Marie",
      "Scarborough–Agincourt",
      "Scarborough Centre",
      "Scarborough–Guildwood",
      "Scarborough–Rouge River",
      "Scarborough Southwest",
      "Simcoe–Grey",
      "Simcoe North",
      "Stormont–Dundas–South Glengarry",
      "Sudbury",
      "Thornhill",
      "Thunder Bay–Rainy River",
      "Thunder Bay–Superior North",
      "Timmins–James Bay",
      "Toronto Centre",
      "Toronto–Danforth",
      "Trinity–Spadina",
      "Vaughan",
      "Welland",
      "Wellington–Halton Hills",
      "Whitby–Oshawa",
      "Willowdale",
      "Windsor–Tecumseh",
      "Windsor West",
      "York Centre",
      "York–Simcoe",
      "York South–Weston",
      "York West",
      "Brandon–Souris",
      "Charleswood–St. James–Assiniboia",
      "Churchill",
      "Dauphin–Swan River–Marquette",
      "Elmwood–Transcona",
      "Kildonan–St. Paul",
      "Portage–Lisgar",
      "Provencher",
      "Saint Boniface",
      "Selkirk–Interlake",
      "Winnipeg Centre",
      "Winnipeg North",
      "Winnipeg South",
      "Winnipeg South Centre",
      "Battlefords–Lloydminster",
      "Blackstrap",
      "Desnethé–Missinippi–Churchill River",
      "Cypress Hills–Grasslands",
      "Palliser",
      "Prince Albert",
      "Regina–Lumsden–Lake Centre",
      "Regina–Qu'Appelle",
      "Saskatoon–Humboldt",
      "Saskatoon–Rosetown–Biggar",
      "Saskatoon–Wanuskewin",
      "Souris–Moose Mountain",
      "Wascana",
      "Yorkton–Melville",
      "Fort McMurray–Athabasca",
      "Calgary East",
      "Calgary Centre-North",
      "Calgary Northeast",
      "Calgary–Nose Hill",
      "Calgary Centre",
      "Calgary Southeast",
      "Calgary Southwest",
      "Calgary West",
      "Crowfoot",
      "Edmonton–Mill Woods–Beaumont",
      "Edmonton Centre",
      "Edmonton East",
      "Edmonton–Leduc",
      "Edmonton–St. Albert",
      "Edmonton–Sherwood Park",
      "Edmonton–Spruce Grove",
      "Edmonton–Strathcona",
      "Lethbridge",
      "Macleod",
      "Medicine Hat",
      "Peace River",
      "Red Deer",
      "Vegreville–Wainwright",
      "Westlock–St. Paul",
      "Wetaskiwin",
      "Wild Rose",
      "Yellowhead",
      "Abbotsford",
      "Burnaby–Douglas",
      "Burnaby–New Westminster",
      "Cariboo–Prince George",
      "Chilliwack–Fraser Canyon",
      "Delta–Richmond East",
      "Pitt Meadows–Maple Ridge–Mission",
      "Esquimalt–Juan de Fuca",
      "Fleetwood–Port Kells",
      "Kamloops–Thompson–Cariboo",
      "Kelowna–Lake Country",
      "Kootenay–Columbia",
      "Langley",
      "Nanaimo–Alberni",
      "Nanaimo–Cowichan",
      "Newton–North Delta",
      "New Westminster–Coquitlam",
      "Okanagan–Shuswap",
      "North Vancouver",
      "Okanagan–Coquihalla",
      "Port Moody–Westwood–Port Coquitlam",
      "Prince George–Peace River",
      "Richmond",
      "Saanich–Gulf Islands",
      "Skeena–Bulkley Valley",
      "British Columbia Southern Interior",
      "South Surrey–White Rock–Cloverdale",
      "Surrey North",
      "Vancouver Centre",
      "Vancouver East",
      "Vancouver Island North",
      "Vancouver Kingsway",
      "Vancouver Quadra",
      "Vancouver South",
      "Victoria",
      "West Vancouver–Sunshine Coast–Sea to Sky Country",
      "Yukon",
      "Western Arctic",
      "Nunavut",      
    ],
    "Alberta" => [
      "Dunvegan-Central Peace-Notley",
      "Lesser Slave Lake",
      "Calgary-Acadia",
      "Calgary-Bow",
      "Calgary-Buffalo",
      "Calgary-Cross",
      "Calgary-Currie",
      "Calgary-East",
      "Calgary-Elbow",
      "Calgary-Fish Creek",
      "Calgary-Foothills",
      "Calgary-Fort",
      "Calgary-Glenmore",
      "Calgary-Greenway",
      "Calgary-Hawkwood",
      "Calgary-Hays",
      "Calgary-Klein",
      "Calgary-Lougheed",
      "Calgary-Mackay-Nose Hill",
      "Calgary-McCall",
      "Calgary-Mountain View",
      "Calgary-North West",
      "Calgary-Northern Hills",
      "Calgary-Shaw",
      "Calgary-South East",
      "Calgary-Varsity",
      "Calgary-West",
      "Edmonton-Beverly-Clareview",
      "Edmonton-Calder",
      "Edmonton-Castle Downs",
      "Edmonton-Centre",
      "Edmonton-Decore",
      "Edmonton-Ellerslie",
      "Edmonton-Glenora",
      "Edmonton-Gold Bar",
      "Edmonton-Highlands-Norwood",
      "Edmonton-Manning",
      "Edmonton-McClung",
      "Edmonton-Meadowlark",
      "Edmonton-Mill Creek",
      "Edmonton-Mill Woods",
      "Edmonton-Riverview",
      "Edmonton-Rutherford",
      "Edmonton-South West",
      "Edmonton-Strathcona",
      "Edmonton-Whitemud",
      "Airdrie",
      "Athabasca-Sturgeon-Redwater",
      "Banff-Cochrane",
      "Barrhead-Morinville-Westlock",
      "Battle River-Wainwright",
      "Bonnyville-Cold Lake",
      "Cardston-Taber-Warner",
      "Chestermere-Rocky View",
      "Cypress-Medicine Hat",
      "Drayton Valley-Devon",
      "Drumheller-Stettler",
      "Fort McMurray-Conklin",
      "Fort McMurray-Wood Buffalo",
      "Fort Saskatchewan-Vegreville",
      "Grande Prairie-Smoky",
      "Grande Prairie-Wapiti",
      "Highwood",
      "Innisfail-Sylvan Lake",
      "Lac La Biche-St. Paul-Two Hills",
      "Lacombe-Ponoka",
      "Leduc-Beaumont",
      "Lethbridge-East",
      "Lethbridge-West",
      "Little Bow",
      "Livingstone-Macleod",
      "Medicine Hat",
      "Olds-Didsbury-Three Hills",
      "Peace River",
      "Red Deer-North",
      "Red Deer-South",
      "Rimbey-Rocky Mountain House-Sundre",
      "Sherwood Park",
      "Spruce Grove-St. Albert",
      "St. Albert",
      "Stony Plain",
      "Strathcona-Sherwood Park",
      "Strathmore-Brooks",
      "Vermilion-Lloydminster",
      "West Yellowhead",
      "Wetaskiwin-Camrose",
      "Whitecourt-Ste. Anne",
    ],
    "British Columbia" => [
      "Abbotsford-Mission",
      "Abbotsford South",
      "Abbotsford West",
      "Alberni-Pacific Rim",
      "Boundary-Similkameen",
      "Burnaby-Deer Lake",
      "Burnaby-Edmonds",
      "Burnaby-Lougheed",
      "Burnaby North",
      "Cariboo-Chilcotin",
      "Cariboo North",
      "Chilliwack",
      "Chilliwack-Hope",
      "Columbia River-Revelstoke",
      "Comox Valley",
      "Coquitlam-Burke Mountain",
      "Coquitlam-Maillardville",
      "Cowichan Valley",
      "Delta North",
      "Delta South",
      "Esquimalt-Royal Roads",
      "Fort Langley-Aldergrove",
      "Fraser-Nicola",
      "Juan de Fuca",
      "Kamloops-North Thompson",
      "Kamloops-South Thompson",
      "Kelowna-Lake Country",
      "Kelowna-Mission",
      "Kootenay East",
      "Kootenay West",
      "Langley",
      "Maple Ridge-Mission",
      "Maple Ridge-Pitt Meadows",
      "Nanaimo",
      "Nanaimo-North Cowichan",
      "Nechako Lakes",
      "Nelson-Creston",
      "New Westminster",
      "North Coast",
      "North Island",
      "North Vancouver-Lonsdale",
      "North Vancouver-Seymour",
      "Oak Bay-Gordon Head",
      "Parksville-Qualicum",
      "Peace River North",
      "Peace River South",
      "Penticton",
      "Port Coquitlam",
      "Port Moody-Coquitlam",
      "Powell River-Sunshine Coast",
      "Prince George-Mackenzie",
      "Prince George-Valemount",
      "Richmond Centre",
      "Richmond East",
      "Richmond-Steveston",
      "Saanich North and the Islands",
      "Saanich South",
      "Shuswap",
      "Skeena",
      "Stikine",
      "Surrey-Cloverdale",
      "Surrey-Fleetwood",
      "Surrey-Green Timbers",
      "Surrey-Newton",
      "Surrey-Panorama",
      "Surrey-Tynehead",
      "Surrey-Whalley",
      "Surrey-White Rock",
      "Vancouver-Fairview",
      "Vancouver-False Creek",
      "Vancouver-Fraserview",
      "Vancouver-Hastings",
      "Vancouver-Kensington",
      "Vancouver-Kingsway",
      "Vancouver-Langara",
      "Vancouver-Mount Pleasant",
      "Vancouver-Point Grey",
      "Vancouver-Quilchena",
      "Vancouver-West End",
      "Vernon-Monashee",
      "Victoria-Beacon Hill",
      "Victoria-Swan Lake",
      "West Vancouver-Capilano",
      "West Vancouver-Sea to Sky",
      "Westside-Kelowna",
    ],
    "Manitoba" => [
      "Agassiz",
      "Arthur-Virden",
      "Assiniboia",
      "Brandon East",
      "Brandon West",
      "Burrows",
      "Charleswood",
      "Concordia",
      "Dauphin",
      "Dawson Trail",
      "Elmwood",
      "Emerson",
      "Flin Flon",
      "Fort Garry-Riverview",
      "Fort Richmond",
      "Fort Rouge",
      "Fort Whyte",
      "Gimli",
      "Interlake",
      "Kewatinook",
      "Kildonan",
      "Kirkfield Park",
      "La Verendrye",
      "Lac du Bonnet",
      "Lakeside",
      "Logan",
      "Midland",
      "Minto",
      "Morden-Winkler",
      "Morris",
      "Point Douglas",
      "Portage la Prairie",
      "Radisson",
      "Riding Mountain",
      "Riel",
      "River East",
      "River Heights",
      "Rossmere",
      "Seine River",
      "Selkirk",
      "Southdale",
      "Spruce Woods",
      "St. Boniface",
      "St. James",
      "St. Johns",
      "St. Norbert",
      "St. Paul",
      "St. Vital",
      "Steinbach",
      "Swan River",
      "The Maples",
      "The Pas",
      "Thompson",
      "Transcona",
      "Tuxedo",
      "Tyndall Park",
      "Wolseley",
    ],
    "New Brunswick" => [
      "Campbellton-Restigouche Centre",
      "Dalhousie-Restigouche East",
      "Nigadoo-Chaleur",
      "Bathurst",
      "Nepisiguit",
      "Caraquet",
      "Lamèque-Shippagan-Miscou",
      "Centre-Péninsule-Saint-Sauveur",
      "Tracadie-Sheila",
      "Miramichi-Bay-Neguac",
      "Miramichi-Bay du Vin",
      "Miramichi Centre",
      "Southwest Miramichi",
      "Rogersville-Kouchibouguac",
      "Kent",
      "Kent South",
      "Shediac-Cap-Pelé",
      "Tantramar",
      "Memramcook-Lakeville-Dieppe",
      "Dieppe Centre-Lewisville",
      "Moncton East",
      "Moncton West",
      "Moncton North",
      "Moncton Crescent",
      "Petitcodiac",
      "Riverview",
      "Albert",
      "Kings East",
      "Hampton-Kings",
      "Quispamsis",
      "Saint John-Fundy",
      "Rothesay",
      "Saint John East",
      "Saint John Harbour",
      "Saint John Portland",
      "Saint John Lancaster",
      "Fundy-River Valley",
      "Charlotte-The Isles",
      "Charlotte-Campobello",
      "Oromocto",
      "Grand Lake-Gagetown",
      "Fredericton-Nashwaaksis",
      "Fredericton-Fort Nashwaak",
      "Fredericton-Lincoln",
      "Fredericton-Silverwood",
      "New Maryland-Sunbury West",
      "York",
      "York North",
      "Woodstock",
      "Carleton",
      "Victoria-Tobique",
      "Grand Falls-Drummond-Saint-André",
      "Restigouche-la-Vallée",
      "Edmundston-Saint-Basile",
      "Madawaska-les-Lacs",
    ],
    "Newfoundland and Labrador" => [
      "Baie Verte—Springdale",
      "Bay of Islands",
      "Bellevue",
      "Bonavista North",
      "Bonavista South",
      "Burgeo—La Poile",
      "Burin—Placentia West",
      "Cape St. Francis",
      "Carbonear—Harbour Grace",
      "Cartwright—L'Anse Au Clair",
      "Conception Bay East—Bell Island",
      "Conception Bay South",
      "Exploits",
      "Ferryland",
      "Fortune Bay—Cape La Hune",
      "Gander",
      "Grand Bank",
      "Grand Falls-Windsor—Buchans",
      "Grand Falls-Windsor—Green Bay South",
      "Harbour Main",
      "Humber East",
      "Humber Valley",
      "Humber West",
      "Kilbride",
      "Labrador West",
      "Lake Melville",
      "Lewisporte",
      "Mount Pearl North",
      "Mount Pearl South",
      "Placentia—St. Mary's",
      "Port au Port",
      "Port De Grave",
      "Signal Hill—Quidi Vidi",
      "St. Barbe",
      "St. George's—Stephenville East",
      "St. John's Centre",
      "St. John's East",
      "St. John's North",
      "St. John's South",
      "St. John's West",
      "Terra Nova",
      "The Isles of Notre Dame",
      "The Straits—White Bay North",
      "Topsail",
      "Torngat Mountains",
      "Trinity—Bay De Verde",
      "Trinity North",
      "Virginia Waters",
    ],
    "Ontario" => [
      "Ajax—Pickering",
      "Algoma—Manitoulin",
      "Ancaster—Dundas—Flamborough—Westdale",
      "Barrie",
      "Beaches—East York",
      "Bramalea—Gore—Malton",
      "Brampton—Springdale",
      "Brampton West",
      "Brant",
      "Bruce—Grey—Owen Sound",
      "Burlington",
      "Cambridge",
      "Carleton—Mississippi Mills",
      "Chatham—Kent—Essex",
      "Davenport",
      "Don Valley East",
      "Don Valley West",
      "Dufferin—Caledon",
      "Durham",
      "Eglinton—Lawrence",
      "Elgin—Middlesex—London",
      "Essex",
      "Etobicoke Centre",
      "Etobicoke—Lakeshore",
      "Etobicoke North",
      "Glengarry—Prescott—Russell",
      "Guelph",
      "Haldimand—Norfolk",
      "Haliburton—Kawartha Lakes—Brock",
      "Halton",
      "Hamilton Centre",
      "Hamilton East—Stoney Creek",
      "Hamilton Mountain",
      "Huron—Bruce",
      "Kenora—Rainy River",
      "Kingston and the Islands",
      "Kitchener Centre",
      "Kitchener—Conestoga",
      "Kitchener—Waterloo",
      "Lambton—Kent—Middlesex",
      "Lanark—Frontenac—Lennoxand Addington",
      "Leeds—Grenville",
      "London—Fanshawe",
      "London North Centre",
      "LondonWest",
      "Markham—Unionville",
      "Mississauga—Brampton South",
      "Mississauga East—Cooksville",
      "Mississauga—Erindale",
      "Mississauga South",
      "Mississauga—Streetsville",
      "Nepean—Carleton",
      "Newmarket—Aurora",
      "Niagara Falls",
      "Niagara West—Glanbrook",
      "Nickel Belt",
      "Nipissing",
      "Northumberland—Quinte West",
      "Oak Ridges—Markham",
      "Oakville",
      "Oshawa",
      "Ottawa Centre",
      "Ottawa—Orléans",
      "Ottawa South",
      "Ottawa—Vanier",
      "Ottawa West—Nepean",
      "Oxford",
      "Parkdale—High Park",
      "Parry Sound—Muskoka",
      "Perth—Wellington",
      "Peterborough",
      "Pickering—Scarborough East",
      "Prince Edward—Hastings",
      "Renfrew—Nipissing—Pembroke",
      "Richmond Hill",
      "St. Catharines",
      "St. Paul's",
      "Sarnia—Lambton",
      "Sault Ste. Marie",
      "Scarborough—Agincourt",
      "Scarborough Centre",
      "Scarborough—Guildwood",
      "Scarborough—Rouge River",
      "Scarborough Southwest",
      "Simcoe—Grey",
      "Simcoe North",
      "Stormont—Dundas—South Glengarry",
      "Sudbury",
      "Thornhill",
      "Thunder Bay—Atikokan",
      "Thunder Bay—Superior North",
      "Timiskaming—Cochrane",
      "Timmins—James Bay",
      "Toronto Centre",
      "Toronto—Danforth",
      "Trinity—Spadina",
      "Vaughan",
      "Welland",
      "Wellington—Halton Hills",
      "Whitby—Oshawa",
      "Willowdale",
      "Windsor—Tecumseh",
      "Windsor West",
      "York Centre",
      "York—Simcoe",
      "York South—Weston",
      "York West",
    ],
    "Nova Scotia" => [
      "Annapolis",
      "Antigonish",
      "Argyle-Barrington",
      "Bedford",
      "Cape Breton Centre",
      "Cape Breton-Richmond",
      "Chester-St. Margaret's",
      "Clare-Digby",
      "Clayton Park West",
      "Colchester-Musquodoboit Valley",
      "Colchester North",
      "Cole Harbour-Eastern Passage",
      "Cole Harbour-Portland Valley",
      "Cumberland North",
      "Cumberland South",
      "Dartmouth East",
      "Dartmouth North",
      "Preston-Dartmouth",
      "Dartmouth South",
      "Guysborough-Eastern Shore-Tracadie",
      "Eastern Shore",
      "Fairview-Clayton Park",
      "Glace Bay",
      "Halifax Armdale",
      "Halifax Atlantic",
      "Halifax Chebucto",
      "Halifax Citadel-Sable Island",
      "Halifax Needham",
      "Hammonds Plains-Lucasville",
      "Hants East",
      "Hants West",
      "Inverness",
      "Kings North",
      "Kings South",
      "Kings West",
      "Lunenburg",
      "Lunenburg West",
      "Northside-Westmount",
      "Pictou Centre",
      "Pictou East",
      "Pictou West",
      "Queens-Shelburne",
      "Sackville-Beaver Bank",
      "Sackville-Cobequid",
      "Sydney-Whitney Pier",
      "Sydney River-Mira-Louisbourg",
      "Timberlea-Prospect",
      "Truro-Bible Hill-Millbrook-Salmon River",
      "Victoria-The Lakes",
      "Waverley-Fall River-Beaver Bank",
      "Yarmouth",
    ],
    "Prince Edward Island" => [
      "Souris-Elmira",
      "Georgetown-St. Peters",
      "Montague-Kilmuir",
      "Belfast-Murray River",
      "Vernon River-Stratford",
      "Stratford-Kinlock",
      "Morell-Mermaid",
      "Tracadie-Hillsborough Park",
      "York-Oyster Bed",
      "Charlottetown-Sherwood",
      "Charlottetown-Parkdale",
      "Charlottetown-Victoria Park",
      "Charlottetown-Brighton",
      "Charlottetown-Lewis Point",
      "West Royalty-Springvale",
      "Cornwall-Meadowbank",
      "Kellys Cross-Cumberland",
      "Rustico-Emerald",
      "Borden-Kinkora",
      "Kensington-Malpeque",
      "Summerside-Wilmot",
      "Summerside-St. Eleanors",
      "Tyne Valley-Linkletter",
      "Evangeline-Miscouche",
      "O'Leary-Inverness",
      "Alberton-Roseville",
      "Tignish-Palmer Road",
    ],
    "Quebec" => [
      "Abitibi-Est",
      "Abitibi-Ouest",
      "Acadie",
      "Anjou-Louis-Riel",
      "Argenteuil",
      "Arthabaska",
      "Beauce-Nord",
      "Beauce-Sud",
      "Beauharnois",
      "Bellechasse",
      "Berthier",
      "Bertrand",
      "Blainville",
      "Bonaventure",
      "Borduas",
      "Bourassa-Sauvé",
      "Bourget",
      "Brome-Missisquoi",
      "Chambly",
      "Champlain",
      "Chapleau",
      "Charlesbourg",
      "Charlevoix-Côte-de-Beaupré",
      "Châteauguay",
      "Chauveau",
      "Chicoutimi",
      "Chomedey",
      "Chutes-de-la-Chaudière",
      "Côte-du-Sud",
      "Crémazie",
      "D'Arcy-McGee",
      "Deux-Montagnes",
      "Drummond-Bois-Francs",
      "Dubuc",
      "Duplessis",
      "Fabre",
      "Gaspé",
      "Gatineau",
      "Gouin",
      "Granby",
      "Groulx",
      "Hochelaga-Maisonneuve",
      "Hull",
      "Huntingdon",
      "Iberville",
      "Îles-de-la-Madeleine",
      "Jacques-Cartier",
      "Jean-Lesage",
      "Jeanne-Mance-Viger",
      "Jean-Talon",
      "Johnson",
      "Joliette",
      "Jonquière",
      "La Peltrie",
      "La Pinière",
      "La Prairie",
      "Labelle",
      "Lac-Saint-Jean",
      "LaFontaine",
      "Laporte",
      "L'Assomption",
      "Laurier-Dorion",
      "Laval-des-Rapides",
      "Laviolette",
      "Lévis",
      "Lotbinière-Frontenac",
      "Louis-Hébert",
      "Marguerite-Bourgeoys",
      "Marie-Victorin",
      "Marquette",
      "Maskinongé",
      "Masson",
      "Matane-Matapédia",
      "Mégantic",
      "Mercier",
      "Mille-Îles",
      "Mirabel",
      "Montarville",
      "Montmorency",
      "Mont-Royal",
      "Nelligan",
      "Nicolet-Bécancour",
      "Notre-Dame-de-Grâce",
      "Orford",
      "Outremont",
      "Papineau",
      "Pointe-aux-Trembles",
      "Pontiac",
      "Portneuf",
      "René-Lévesque",
      "Repentigny",
      "Richelieu",
      "Richmond",
      "Rimouski",
      "Rivière-du-Loup-Témiscouata",
      "Robert-Baldwin",
      "Roberval",
      "Rosemont",
      "Rousseau",
      "Rouyn-Noranda-Témiscamingue",
      "Sainte-Marie-Saint-Jacques",
      "Sainte-Rose",
      "Saint-François",
      "Saint-Henri-Sainte-Anne",
      "Saint-Hyacinthe",
      "Saint-Jean",
      "Saint-Jérôme",
      "Saint-Laurent",
      "Saint-Maurice",
      "Sanguinet",
      "Sherbrooke",
      "Soulanges",
      "Taillon",
      "Taschereau",
      "Terrebonne",
      "Trois-Rivières",
      "Ungava",
      "Vachon",
      "Vanier-Les Rivières",
      "Vaudreuil",
      "Verchères",
      "Verdun",
      "Viau",
      "Vimont",
      "Westmount-Saint-Louis",
    ],
    "Saskatchewan" => [
      "Arm River-Watrous",
      "Athabasca",
      "Batoche",
      "Biggar",
      "Cannington",
      "Canora-Pelly",
      "Carrot River Valley",
      "Cumberland",
      "Cut Knife-Turtleford",
      "Cypress Hills",
      "Estevan",
      "Humboldt",
      "Indian Head-Milestone",
      "Kelvington-Wadena",
      "Kindersley",
      "Last Mountain-Touchwood",
      "Lloydminster",
      "Martensville",
      "Meadow Lake",
      "Melfort",
      "Melville-Saltcoats",
      "Moose Jaw North",
      "Moose Jaw Wakamow",
      "Moosomin",
      "Prince Albert Carlton",
      "Prince Albert Northcote",
      "Regina Coronation Park",
      "Regina Dewdney",
      "Regina Douglas Park",
      "Regina Elphinstone-Centre",
      "Regina Lakeview",
      "Regina Northeast",
      "Regina Qu'Appelle Valley",
      "Regina Rosemont",
      "Regina South",
      "Regina Walsh Acres",
      "Regina Wascana Plains",
      "Rosetown-Elrose",
      "Rosthern-Shellbrook",
      "Saskatchewan Rivers",
      "Saskatoon Centre",
      "Saskatoon Eastview",
      "Saskatoon Fairview",
      "Saskatoon Greystone",
      "Saskatoon Massey Place",
      "Saskatoon Meewasin",
      "Saskatoon Northwest",
      "Saskatoon Nutana",
      "Saskatoon Riversdale",
      "Saskatoon Silver Springs",
      "Saskatoon Southeast",
      "Saskatoon Sutherland",
      "Swift Current",
      "The Battlefords",
      "Thunder Creek",
      "Weyburn-Big Muddy",
      "Wood River",
      "Yorkton",
    ],
  }
end
